# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
inhibit_all_warnings!

target 'EngagementSample' do
  use_frameworks!

  pod 'PWEngagement', '~> 3.10.0'
end
